### ISSUE TITLE
start project plan

### ISSUE THREAD

**Issue by npscience** [npscience/equitable-preprints#3]
start a project plan in this repo

e.g. 
- [ ] consider tool design & required data / skills
- [ ] contact likely candidates to join project at sprint
- [ ] contact potential remote contributors #4
